####################################
# Sample for testing               #
####################################
key=value

####################################
# Database Settings                #
####################################
Database.url = jdbc:mysql://uranus/crystal
Database.driver.class = com.mysql.cj.jdbc.Driver
Database.user = crystal
Database.password = 9241892
Database.UseDriver = false
# DataSource JNDI name for the Crystal framework. This is used to get the DataSource from the JNDI context.
DataSource.UseDataSource = true
DataSource.JNDI = java:/CrystalDS

####################################
# System Settings                  #
####################################
System.PathToSQLDirectory = sql/